joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

yawl_joint_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: yawl_joint
    pid: {p: 0.5, i: 0.0, d: 0.05}

vertical_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: vertical_joint
    pid: {p: 60.0, i: 0.0, d: 20.0}

pitch_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: pitch_joint
    pid: {p: 0.1, i: 0.0, d: 0.8}